// Copyright (c) 2025 Varshith Gudur. Licensed under MIT OR Apache-2.0.
//
// `@valori/api-types` — the ONE TypeScript model of the Valori Data Plane
// REST API v1.
//
// Before Phase API-2 there were two byte-identical, hand-written copies of a
// `types/valori.ts` (one under `ui/src/`, one under `ui/studio/src/`) that
// drifted from the wire and invented fields the server never emits
// (`SearchResponse.state_hash`, a hardcoded `ClusterStatus.converged`, a
// client-side `queried_at` presented as server state). This package replaces
// both. It is generated, not written:
//
//     ./scripts/generate-api-types.sh
//
// which runs `openapi-typescript` over `api/openapi/valori-v1.yaml` into
// `./src/valori-v1.ts`. That file is machine output — never hand-edit it.
//
// This index exists only to give the generated `components["schemas"][...]`
// index types the short, ergonomic aliases the UI already uses. Every alias
// below resolves into the generated tree, so a contract change that renames or
// removes a schema is a TypeScript error here rather than silent drift.

import type { components, paths, operations } from "./valori-v1.js";

export type { components, paths, operations };

type Schemas = components["schemas"];

// ── Wire models — every one of these is emitted by valori-node ──────────────

// Phase API-3.1: the contract is now generated end-to-end from Rust, so a
// schema's name in this file is the Rust type's name. Several aliases below
// therefore point at a different generated name than they did when the
// contract was hand-maintained — the alias (the left-hand side) is unchanged,
// so nothing downstream had to move.
//
// Aliases dropped in API-3.1 because the generated contract has no such
// schema and nothing in `ui/` imported them: `Metric`, `IndexKind`,
// `IndexType`, `IndexState`, `Consistency`, `InsertReceipt`, `EventLogProof`.
// `metric` and index-kind are plain strings on the wire, not closed enums, so
// there was never a schema to alias. If one is added later it will appear here
// as a generated name.

export type Error = Schemas["ApiError"];
export type ErrorCode = Schemas["ErrorCode"];

export type Collection = Schemas["CollectionInfo"];
export type CreateCollectionRequest = Schemas["CreateCollectionRequest"];
export type ListCollectionsResponse = Schemas["ListCollectionsResponse"];
export type CreateCollectionResponse = Schemas["CreateCollectionResponse"];

export type InsertRecordRequest = Schemas["InsertRecordRequest"];
export type InsertRecordResponse = Schemas["InsertRecordResponse"];
export type InsertReceiptJson = Schemas["InsertReceiptJson"];

export type SearchRequest = Schemas["SearchRequest"];
export type SearchResponse = Schemas["SearchResponse"];
export type SearchHit = Schemas["SearchHit"];
export type MultiSearchRequest = Schemas["MultiSearchRequest"];
export type MultiSearchResponse = Schemas["MultiSearchResponse"];
export type MultiSearchHit = Schemas["MultiSearchHit"];

export type Health = Schemas["HealthResponse"];
/** The Raft view served by `GET /v1/cluster/status`. */
export type ClusterStatus = Schemas["StatusView"];

/** `GET /v1/proof/state`. */
export type ProofResponse = Schemas["StateProofResponse"];
export type IndexStatus = Schemas["IndexStatusResponse"];
export type EventProof = Schemas["EventProofResponse"];
export type PoolStats = Schemas["PoolStatsSchema"];

// ── UI-layer view models — NOT wire types ──────────────────────────────────
//
// These describe values the UI's own Next.js BFF routes or React hooks add on
// top of a server response. They live here, clearly separated, so nobody is
// tempted to put them back into the wire model where they would read as
// something the node emits.

/** A `SearchResponse` after `ui/src/app/api/search/route.ts` stamps its own
 *  client-side receive time onto it. `queried_at` is generated by the BFF —
 *  the node never sends it. */
export type AnnotatedSearchResponse = SearchResponse & {
  /** ISO-8601 timestamp stamped by the UI's BFF route on receipt. Not server state. */
  queried_at?: string;
};

/** Cluster view state as `useCluster` computes it. `converged` is *derived* by
 *  comparing every member's `last_applied_index`; the node has no `converged`
 *  field and never claims convergence itself. */
export type ClusterView = {
  leaderId?: number;
  members: NonNullable<ClusterStatus["members"]>;
  /** Derived client-side: true when every member reports the same applied index. */
  converged: boolean;
};

/** A `SearchHit` after the UI's own metadata-sidecar lookup
 *  (`GET /api/meta?target_id=record:<id>`) attaches display text. Neither
 *  field is part of the node's `SearchHit` — they come from the sidecar, which
 *  is not replicated and not part of the audit chain. */
export type EnrichedSearchHit = SearchHit & {
  /** Chunk body text from the metadata sidecar. Client-side enrichment. */
  text?: string;
  /** Source document path from the metadata sidecar. Client-side enrichment. */
  source?: string;
};
