// Copyright (c) 2025 Varshith Gudur. Licensed under MIT OR Apache-2.0.
//
// Phase API-2: this file used to be a hand-written mirror of the Rust API
// response shapes, byte-identical to a second copy under `ui/studio/src/`.
// Both copies had drifted from the wire:
//
//   * `SearchResponse.state_hash` — the node has never emitted it on
//     `/v1/search`; only the as-of variant returns `as_of_state_hash`.
//   * `SearchResponse.queried_at` — generated by this app's own BFF route
//     (`app/api/search/route.ts`), not by the node.
//   * `ClusterStatus.converged` — derived in `useCluster` from every member's
//     applied index; the node has no such field.
//   * `SearchResult.text` / `.source` — not fields of the node's `SearchHit`.
//
// The wire model now comes from `@valori/api-types`, generated from
// `api/openapi/valori-v1.yaml` (see `scripts/generate-api-types.sh`). The
// aliases below exist only so the existing imports in this app keep working.

export type {
  Collection,
  Error as ApiError,
  ErrorCode,
  Health as HealthResponse,
  ClusterStatus,
  SearchRequest,
  SearchResponse,
  SearchHit as SearchResult,
  MultiSearchHit,
  InsertRecordRequest,
  InsertRecordResponse,
  IndexStatus,
  ProofResponse,
  PoolStats,
  // View models — explicitly NOT wire types.
  AnnotatedSearchResponse,
  ClusterView,
} from "@valori/api-types";
